#ifndef __GLOBAL_CONSTANTS_H__
#define __GLOBAL_CONSTANTS_H__

// These are just here to spell out the value being used
#define MILLISECONDS_PER_SECOND 1000
#define MICROSECONDS_PER_MILLISECOND 1000
#define MICROSECONDS_PER_SECOND (MILLISECONDS_PER_SECOND * MICROSECONDS_PER_MILLISECOND)

#endif // __GLOBAL_CONSTANTS_H__
